### PR TITLE
Try building on latest python versions

### PR DESCRIPTION
**Pull request by Colin-b**
Hello @maartendp @maarten-dp , 

Would it be possible to get maintainer access to this project and the datamodel one?

Thanks again

### CODE REVIEW

**Comment by maarten-dp** [comment]
Hi Colin,

While I understand your request, I have a hard time granting it.
The main reason being that I'm entrusting something that I've spent a lot of personal time on, to someone that I effectively know nothing about.

I don't want to be put in a situation where the codebase is taking a direction that I don't agree with.

I propose we work with PRs for a while to build up trust, and that I make a promise to commit to being (reasonably) active in handling these PRs.

Note that these are my current thoughts. Feel free to add to this discussion.

Kind regards

**Comment by Colin-b** [comment]
That makes total sense, I was under the assumption that you would not want to maintain this project anymore.
Knowing your position I won't hesitate to come up with PRs if there is a need for :)
Thanks

**Comment by maarten-dp** [comment]
Hi Colin, would you still be interested in getting maintainer access? I'm definitely being a limiting factor here, something which I promised I wouldn't be. As such it's only normal that I let someone maintain it that is actually using the code.

**Comment by Colin-b** [comment]
Thanks for the proposal, I'll discuss it with @JesseDeLoore first thing next week and we will come back to you if that's ok with you?

**Comment by JesseDeLoore** [comment]
I had a small chat with Colin.
We both value your (@maarten-dp) involvement highly. 
We don't experience you as a blocker on the project and are happy to do the leg work (prep prs and such) while having you as the final arbiter and reviewer.
It would be nice to have at least one (or both) of us added as a maintainer, in case you actaully become hard to reach and we need to make modifications.
Currently all modifications are not urgent, so we aren't on a tight schedule to push them through.

**Pull request closed without merging**
